import { v } from "convex/values";
import { internalMutation, internalQuery, mutation, query } from "./_generated/server";
import { requireUserId } from "./_shared/auth";
import { fail } from "./_shared/errors";

const hash = async (value: string) => [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))].map((v) => v.toString(16).padStart(2, "0")).join("");
const makeToken = () => `tu_live_${btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "")}`;
const TOKEN_LIFETIME_MS = 90 * 24 * 60 * 60 * 1000;

export const issue = mutation({ args: {}, handler: async (ctx) => { const userId = await requireUserId(ctx); const business = await ctx.db.query("businesses").withIndex("by_business_id", (q) => q.eq("businessId", userId)).unique(); if (!business) fail("BUSINESS_NOT_FOUND", "Buat usaha terlebih dahulu."); const now = Date.now(); for (const item of await ctx.db.query("agentTokens").withIndex("by_business_created", (q) => q.eq("businessId", userId)).order("desc").take(20)) if (!item.revokedAt) await ctx.db.patch(item._id, { revokedAt: now }); const token = makeToken(); const expiresAt = now + TOKEN_LIFETIME_MS; await ctx.db.insert("agentTokens", { businessId: userId, tokenHash: await hash(token), tokenPrefix: token.slice(0, 14), createdAt: now, expiresAt }); await ctx.db.insert("aiActionLogs", { businessId: userId, action: "issue_agent_token", inputSummary: "Token akses Agent GPT baru diterbitkan.", outputSummary: `Token ${token.slice(0, 14)}… aktif; token lama dicabut.`, requiresVerification: true, createdAt: now }); return { token, expiresAt }; } });
export const configuration = query({ args: {}, handler: async (ctx) => { const userId = await requireUserId(ctx); const business = await ctx.db.query("businesses").withIndex("by_business_id", (q) => q.eq("businessId", userId)).unique(); if (!business) fail("BUSINESS_NOT_FOUND", "Buat usaha terlebih dahulu."); const products = await ctx.db.query("products").withIndex("by_business_slug", (q) => q.eq("businessId", userId)).take(50); const token = (await ctx.db.query("agentTokens").withIndex("by_business_created", (q) => q.eq("businessId", userId)).order("desc").take(20)).find((item) => !item.revokedAt && (!item.expiresAt || item.expiresAt > Date.now())); return { businessName: business.name, products: products.map(({ name, price }) => ({ name, price })), serverUrl: process.env.CONVEX_SITE_URL ?? "", token: token ? { prefix: token.tokenPrefix, createdAt: token.createdAt, expiresAt: token.expiresAt ?? null } : null }; } });
export const resolve = internalQuery({ args: { token: v.string() }, handler: async (ctx, args) => { const tokenHash = await hash(args.token); const item = await ctx.db.query("agentTokens").withIndex("by_token_hash", (q) => q.eq("tokenHash", tokenHash)).unique(); return item && !item.revokedAt && (!item.expiresAt || item.expiresAt > Date.now()) ? { businessId: item.businessId } : null; } });
export const logRead = internalMutation({ args: { businessId: v.string(), action: v.string() }, handler: async (ctx, args) => { await ctx.db.insert("aiActionLogs", { businessId: args.businessId, action: args.action, inputSummary: "GPT membaca data usaha.", outputSummary: "Action GPT berhasil membaca data.", requiresVerification: false, createdAt: Date.now() }); } });
export const businessProfile = internalQuery({ args: { businessId: v.string() }, handler: async (ctx, args) => ctx.db.query("businesses").withIndex("by_business_id", (q) => q.eq("businessId", args.businessId)).unique() });
export const listProducts = internalQuery({ args: { businessId: v.string() }, handler: async (ctx, args) => ctx.db.query("products").withIndex("by_business_slug", (q) => q.eq("businessId", args.businessId)).take(50) });
export const updateBusinessFromToken = internalMutation({ args: { businessId: v.string(), name: v.string() }, handler: async (ctx, args) => { const business = await ctx.db.query("businesses").withIndex("by_business_id", (q) => q.eq("businessId", args.businessId)).unique(); const name = args.name.trim(); if (!business || !name) fail("INVALID_NAME", "Nama usaha wajib diisi."); await ctx.db.patch(business._id, { name }); await ctx.db.insert("aiActionLogs", { businessId: args.businessId, action: "update_business", inputSummary: "GPT memperbarui nama usaha.", outputSummary: "Profil usaha diperbarui.", requiresVerification: true, createdAt: Date.now() }); } });
export const createProductFromToken = internalMutation({ args: { businessId: v.string(), name: v.string(), price: v.number(), stock: v.number(), lowStockThreshold: v.number() }, handler: async (ctx, args) => { const name = args.name.trim(); if (!name || args.price < 0 || args.stock < 0 || args.lowStockThreshold < 0) fail("VALIDATION_ERROR", "Data produk tidak valid."); const products = await ctx.db.query("products").withIndex("by_business_slug", (q) => q.eq("businessId", args.businessId)).take(51); if (products.length >= 50) fail("TOO_MANY_PRODUCTS", "Maksimal 50 produk."); const base = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "produk"; let slug = base; let suffix = 2; while (products.some((product) => product.slug === slug)) slug = `${base}-${suffix++}`; await ctx.db.insert("products", { businessId: args.businessId, slug, name, price: Math.round(args.price), stock: Math.round(args.stock), lowStockThreshold: Math.round(args.lowStockThreshold), sortOrder: products.length }); await ctx.db.insert("aiActionLogs", { businessId: args.businessId, action: "create_product", inputSummary: "GPT menambah produk.", outputSummary: `Produk ${name} ditambahkan.`, requiresVerification: true, createdAt: Date.now() }); } });
export const updateProductFromToken = internalMutation({ args: { businessId: v.string(), productId: v.string(), name: v.string(), price: v.number(), stock: v.number(), lowStockThreshold: v.number() }, handler: async (ctx, args) => { const productId = ctx.db.normalizeId("products", args.productId); const product = productId ? await ctx.db.get(productId) : null; const name = args.name.trim(); if (!product || product.businessId !== args.businessId) fail("PRODUCT_NOT_FOUND", "Produk tidak ditemukan."); if (!name || args.price < 0 || args.stock < 0 || args.lowStockThreshold < 0) fail("VALIDATION_ERROR", "Data produk tidak valid."); await ctx.db.patch(productId!, { name, price: Math.round(args.price), stock: Math.round(args.stock), lowStockThreshold: Math.round(args.lowStockThreshold) }); await ctx.db.insert("aiActionLogs", { businessId: args.businessId, action: "update_product", inputSummary: "GPT memperbarui produk.", outputSummary: `Produk ${name} diperbarui.`, requiresVerification: true, createdAt: Date.now() }); } });
export const removeProductFromToken = internalMutation({ args: { businessId: v.string(), productId: v.string() }, handler: async (ctx, args) => { const productId = ctx.db.normalizeId("products", args.productId); const product = productId ? await ctx.db.get(productId) : null; if (!product || product.businessId !== args.businessId) fail("PRODUCT_NOT_FOUND", "Produk tidak ditemukan."); await ctx.db.delete(productId!); await ctx.db.insert("aiActionLogs", { businessId: args.businessId, action: "delete_product", inputSummary: "GPT menghapus produk.", outputSummary: `Produk ${product.name} dihapus.`, requiresVerification: true, createdAt: Date.now() }); } });
