"use client";

import { Check, Copy, Download, KeyRound } from "lucide-react";
import { useMutation, useQuery } from "convex/react";
import { useState } from "react";
import { api } from "@/convex/_generated/api";
import { Button } from "@/components/ui/button";
import { useDashboardLocale } from "./dashboard-locale";

function actionSchema(businessName: string, serverUrl: string) {
  const error = { description: "Request failed.", content: { "application/json": { schema: { type: "object", properties: { error: { type: "object", properties: { code: { type: "string" }, message: { type: "string" } } } } } } } };
  const order = { type: "object", properties: { _id: { type: "string" }, customerName: { type: "string" }, total: { type: "number" }, paymentStatus: { type: "string", enum: ["UNPAID", "PAID", "PARTIAL"] }, fulfillmentStatus: { type: "string", enum: ["PENDING", "COMPLETED"] }, pickupTime: { type: "string", format: "date-time" } } };
  return {
    openapi: "3.1.0",
    info: { title: `Asisten Pribadi AI Agent — ${businessName}`, version: "1.0.0", description: "Manage orders, stock, and summaries only for the workspace that owns this token." },
    servers: [{ url: serverUrl }],
    security: [{ ApiKeyAuth: [] }],
    paths: {
      "/api/agent/orders": {
        get: { operationId: "list_pending_orders", summary: "List pending orders", description: "Read PENDING orders owned by the token's workspace.", "x-openai-isConsequential": false, responses: { "200": { description: "Pending orders.", content: { "application/json": { schema: { type: "object", properties: { orders: { type: "array", items: order } } } } } }, "401": error } },
        post: { operationId: "create_order", summary: "Create an order and reduce stock", description: "After user confirmation, atomically create an order in the token owner's workspace.", "x-openai-isConsequential": true, requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["requestId", "customerName", "items", "pickupTime", "paymentStatus"], properties: { requestId: { type: "string", description: "Unique ID for safe retries." }, customerName: { type: "string" }, items: { type: "array", minItems: 1, items: { type: "object", required: ["product", "quantity"], properties: { product: { type: "string" }, quantity: { type: "integer", minimum: 1 } } } }, pickupTime: { type: "string", format: "date-time" }, paymentStatus: { type: "string", enum: ["UNPAID", "PAID", "PARTIAL"] }, notes: { type: "string" } } } } } }, responses: { "201": { description: "Order created." }, "200": { description: "Idempotent replay." }, "400": error, "401": error, "409": error } },
      },
      "/api/agent/orders/{id}": { patch: { operationId: "update_order", summary: "Update order status", description: "After user confirmation, update an order owned by the token's workspace.", "x-openai-isConsequential": true, parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" }, description: "Order ID." }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", minProperties: 1, additionalProperties: false, properties: { fulfillmentStatus: { type: "string", enum: ["PENDING", "COMPLETED"] }, paymentStatus: { type: "string", enum: ["UNPAID", "PAID", "PARTIAL"] } } } } } }, responses: { "200": { description: "Order updated.", content: { "application/json": { schema: { type: "object", properties: { order } } } } }, "400": error, "401": error, "404": error } } },
      "/api/agent/inventory/low-stock": { get: { operationId: "get_low_stock_items", summary: "List low-stock products", description: "Read products at or below the token owner's stock threshold.", "x-openai-isConsequential": false, responses: { "200": { description: "Low-stock products." }, "401": error } } },
      "/api/agent/summary/today": { get: { operationId: "get_daily_summary", summary: "Today's summary", description: "Read today's summary in the Asia/Jakarta time zone for the token owner's workspace.", "x-openai-isConsequential": false, responses: { "200": { description: "Today's summary." }, "401": error } } },
      "/api/agent/business": { get: { operationId: "get_business_profile", summary: "Read workspace profile", description: "Read the token owner's workspace profile.", "x-openai-isConsequential": false, responses: { "200": { description: "Workspace profile." }, "401": error } }, patch: { operationId: "update_business_profile", summary: "Update workspace name", description: "After user confirmation, update the token owner's workspace name.", "x-openai-isConsequential": true, requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name"], properties: { name: { type: "string" } } } } } }, responses: { "200": { description: "Profile updated." }, "400": error, "401": error } } },
      "/api/agent/products": { get: { operationId: "list_products", summary: "List product catalog", description: "Read the token owner's full product catalog.", "x-openai-isConsequential": false, responses: { "200": { description: "Product catalog." }, "401": error } }, post: { operationId: "create_product", summary: "Create product", description: "After user confirmation, add a product to the token owner's catalog.", "x-openai-isConsequential": true, requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "price", "stock", "lowStockThreshold"], properties: { name: { type: "string" }, price: { type: "number", minimum: 0 }, stock: { type: "number", minimum: 0 }, lowStockThreshold: { type: "number", minimum: 0 } } } } } }, responses: { "201": { description: "Product created." }, "400": error, "401": error } } },
      "/api/agent/products/{id}": { patch: { operationId: "update_product", summary: "Update product", description: "After user confirmation, update a product owned by the token's workspace.", "x-openai-isConsequential": true, parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["name", "price", "stock", "lowStockThreshold"], properties: { name: { type: "string" }, price: { type: "number", minimum: 0 }, stock: { type: "number", minimum: 0 }, lowStockThreshold: { type: "number", minimum: 0 } } } } } }, responses: { "200": { description: "Product updated." }, "400": error, "401": error, "404": error } }, delete: { operationId: "delete_product", summary: "Delete product", description: "After user confirmation, delete a product owned by the token's workspace.", "x-openai-isConsequential": true, parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Product deleted." }, "401": error, "404": error } } },
    },
    components: { schemas: {}, securitySchemes: { ApiKeyAuth: { type: "apiKey", in: "header", name: "X-Action-API-Key", description: "This workspace's Agent Setup token." } } },
  };
}

function builderDetails(businessName: string, products: Array<{ name: string; price: number }>) {
  return {
    name: `Asisten ${businessName}`,
    description: `A personal assistant for ${businessName}. It records orders, checks stock, and summarizes the latest workspace data.`,
    instructions: `# Role\n\nYou are the personal assistant for ${businessName}. Answer briefly, clearly, and concretely in English unless the user asks for another language.\n\n# Scope\n\nWork only for ${businessName}. You can manage summaries, pending orders, low stock, the workspace profile, and the product catalog. Never use demo data or mention another workspace.\n\n# Action selection\n\nSummary → get_daily_summary. Low stock → get_low_stock_items. Pending orders → list_pending_orders. Workspace profile → get_business_profile or update_business_profile. Catalog → list_products, create_product, update_product, or delete_product. Never call an irrelevant Action.\n\n# Source of truth\n\nPrices, stock, totals, and statuses must come from the latest Action. Never guess or claim a change before the Action succeeds. Never request, display, or place an API key/token in the conversation or response.\n\n# Mutations\n\nBefore creating, updating, or deleting an order, profile, or product: show the real data that will change and wait for explicit confirmation. Never invent an example ID. If an order or product ID is unknown, call the relevant list first. For a new order, create a fresh UUID requestId after confirmation; after a timeout, retry the identical payload with the same requestId.\n\n# Response\n\nAfter an Action succeeds, summarize the action and result briefly. If it fails, explain the safe API message and ask for the minimum correction. Never promise payments, message delivery, order cancellation, accounting, or operations outside the Actions.`,
    starters: [
      `What is the summary for ${businessName} today?`,
      "Which orders are still pending?",
      "Which stock needs attention?",
      "I want to record a new order.",
    ],
    settings: "Knowledge: empty\nRecommended model: No Recommended Model\nCapabilities: Web Search off, Canvas off, Image Generation off, Code Interpreter & Data Analysis off\nAuthentication: API Key → Custom header → X-Action-API-Key",
    knowledge: `# ${businessName}\n\nThis assistant only supports the ${businessName} workspace. Use Actions as the source of truth for orders, stock, and today's summary. Never use another workspace's data or demo data.\n\n## Catalog when this file was created\n\n${products.length ? products.map((product) => `- ${product.name}: Rp${product.price.toLocaleString("id-ID")}`).join("\n") : "No products yet."}\n\n## Safety boundary\n\nAsk for explicit confirmation before creating or changing an order. Never request or display an API key or token.`,
  };
}

export function AgentSetup() {
  const { formatLocale, text } = useDashboardLocale();
  const config = useQuery(api.agent.configuration);
  const issue = useMutation(api.agent.issue);
  const [token, setToken] = useState("");
  const [tokenExpiresAt, setTokenExpiresAt] = useState<number | null>(null);
  const [copied, setCopied] = useState("");
  const [tab, setTab] = useState("name");
  if (!config) return <p className="text-sm text-muted-foreground">{text("Loading assistant guide…", "Memuat panduan asisten…")}</p>;

  const details = builderDetails(config.businessName, config.products);
  const schema = JSON.stringify(actionSchema(config.businessName, config.serverUrl), null, 2);
  const copy = async (id: string, value: string) => { await navigator.clipboard.writeText(value); setCopied(id); };
  const fields = [
    ["name", text("GPT name", "Nama GPT"), details.name],
    ["description", text("Description", "Deskripsi"), details.description],
    ["instructions", text("Instructions", "Instruksi"), details.instructions],
    ["starters", text("Conversation starters", "Pembuka percakapan"), details.starters.join("\n")],
    ["settings", text("GPT settings", "Pengaturan GPT"), details.settings],
    ["integration", text("Connect Action", "Hubungkan Action"), ""],
  ] as const;
  const active = fields.find(([id]) => id === tab) ?? fields[0];
  const downloadKnowledge = () => {
    const href = URL.createObjectURL(new Blob([details.knowledge], { type: "text/markdown" }));
    const link = document.createElement("a"); link.href = href; link.download = `${config.businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-knowledge.md`; link.click(); URL.revokeObjectURL(href);
  };

  return <section className="w-full border-y border-border py-6">
    <div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-medium uppercase tracking-widest text-accent">{text("Set up an AI assistant", "Siapkan asisten AI")}</p><h2 className="mt-2 text-xl font-semibold break-words">{text("Connect GPT to", "Hubungkan GPT ke")} {config.businessName}</h2><p className="mt-2 text-sm text-muted-foreground">{text("Follow these steps in order. Technical details appear only when needed.", "Ikuti langkah berikut berurutan. Detail teknis tersedia hanya saat dibutuhkan.")}</p></div><KeyRound className="shrink-0 text-accent" /></div>
    <ol className="mt-6 grid overflow-hidden rounded-md border border-border sm:grid-cols-3 sm:divide-x sm:divide-y-0 divide-y divide-border">
      {[text("Copy the GPT identity and instructions", "Salin identitas dan instruksi GPT"), text("Add the Action and token", "Tambahkan Action dan token"), text("Test the summary and orders", "Uji ringkasan serta pesanan")].map((step, index) => <li className="flex gap-3 p-4 text-sm" key={step}><span className="text-accent">{index + 1}.</span>{step}</li>)}
    </ol>
    {/* TODO(rr): underline tabs (border-b-2 active marker); shadcn Button has no underline-tab variant, kept raw to avoid fighting utilities. */}
    <div className="mt-6 flex max-w-full overflow-x-auto border-b border-border" role="tablist" aria-label={text("GPT Builder details", "Detail GPT Builder")}>{fields.map(([id, label]) => <button className={`min-h-11 shrink-0 border-b-2 px-3 py-2 text-sm ${tab === id ? "border-accent text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`} key={id} onClick={() => setTab(id)} role="tab" aria-selected={tab === id}>{label}</button>)}</div>
    {tab !== "integration" ? <div className="mt-6 rounded-md border border-border bg-muted/30 p-4 sm:p-5" role="tabpanel"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{active[1]}</h3><Button className="pointer-coarse:min-h-11" size="sm" variant="outline" onClick={() => void copy(active[0], active[2])}>{copied === active[0] ? <Check /> : <Copy />}{copied === active[0] ? text("Copied", "Tersalin") : text("Copy all", "Salin semua")}</Button></div>{active[0] === "starters" ? <div className="mt-4 space-y-2">{details.starters.map((starter, index) => <div className="flex items-center justify-between gap-3 rounded-md border border-border bg-background p-3 text-sm" key={starter}><span>{starter}</span><Button className="pointer-coarse:min-h-11" size="xs" variant="outline" onClick={() => void copy(`starter-${index}`, starter)}>{copied === `starter-${index}` ? <Check /> : <Copy />}{copied === `starter-${index}` ? text("Copied", "Tersalin") : text("Copy", "Salin")}</Button></div>)}</div> : <pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs text-muted-foreground">{active[2]}</pre>}</div> : null}
    <div className={`mt-6 space-y-6 ${tab === "integration" ? "block" : "hidden"}`}><div className="rounded-md border border-border p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">{text("GPT knowledge", "Pengetahuan GPT")}</h3><p className="mt-1 text-xs text-muted-foreground">{text("Optional: download and upload it to Knowledge in GPT Builder.", "Opsional: unduh lalu unggah ke bagian Knowledge di GPT Builder.")}</p></div><Button className="pointer-coarse:min-h-11" size="sm" variant="outline" onClick={downloadKnowledge}><Download />{text("Download .md", "Unduh .md")}</Button></div></div>
    <div className="rounded-md border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">{text("Action and token", "Action dan token")}</h3><p className="mt-1 text-xs text-muted-foreground">{text("Paste the schema into the Action, then enter the token as an API Key with a custom header.", "Tempel schema pada Action, lalu masukkan token sebagai API Key dengan custom header.")}</p>{config.token ? <p className="mt-2 text-xs text-muted-foreground">{text("Active token", "Token aktif")}: {config.token.prefix}… · {text("created", "dibuat")} {new Date(config.token.createdAt).toLocaleDateString(formatLocale)} · {config.token.expiresAt ? `${text("expires", "berakhir")} ${new Date(config.token.expiresAt).toLocaleDateString(formatLocale)}` : text("no expiry", "tanpa masa berlaku")}</p> : null}</div><div className="flex gap-2"><Button className="pointer-coarse:min-h-11" size="sm" onClick={async () => { const result = await issue(); setToken(result.token); setTokenExpiresAt(result.expiresAt); }}>{text("Create new token", "Buat token baru")}</Button><Button className="pointer-coarse:min-h-11" size="sm" variant="outline" onClick={() => void copy("schema", schema)}>{copied === "schema" ? <Check /> : <Copy />}{copied === "schema" ? text("Copied", "Tersalin") : text("Copy schema", "Salin schema")}</Button></div></div>{token && <div className="mt-4 rounded-md border border-accent bg-secondary p-4"><p className="text-sm font-semibold">{text("Token shown only once", "Token hanya ditampilkan sekali")}</p><p className="mt-1 text-xs text-muted-foreground">{text("Copy it now. Token expires", "Salin sekarang. Token berakhir")} {tokenExpiresAt ? new Date(tokenExpiresAt).toLocaleDateString(formatLocale) : text("according to policy", "sesuai kebijakan")}.</p><code className="mt-2 block break-all text-xs">{token}</code><Button className="mt-3 pointer-coarse:min-h-11" onClick={() => void copy("token", token)} size="sm">{copied === "token" ? <Check /> : <Copy />}{copied === "token" ? text("Copied", "Tersalin") : text("Copy token", "Salin token")}</Button></div>}<details className="mt-5 rounded-md bg-muted p-4 text-xs"><summary className="cursor-pointer font-medium">{text("View technical schema", "Lihat schema teknis")}</summary><pre className="mt-4 max-h-72 overflow-auto whitespace-pre-wrap break-words">{schema}</pre></details></div></div>
  </section>;
}
