export const locales = ["id", "en", "fr", "ja"] as const;
export type Locale = (typeof locales)[number];

export const languageNames: Record<Locale, string> = {
  id: "Bahasa Indonesia",
  en: "English",
  fr: "Français",
  ja: "日本語",
};

export function getLocale(value?: string): Locale {
  return locales.includes(value as Locale) ? (value as Locale) : "id";
}

export const landingCopy = {
  id: {
    signIn: "Masuk",
    language: "Bahasa",
    eyebrow: "Asisten operasional untuk UMKM",
    title: "Kelola pesanan dan stok lewat percakapan.",
    description: "TemanUsaha menghubungkan GPT dengan data usaha Anda agar pesanan, stok, dan ringkasan harian tetap rapi dan dapat diperiksa.",
    demoCta: "Coba demo interaktif",
    dashboardCta: "Buka dashboard usaha",
    deployCta: "Deploy sendiri",
    separation: "Data demo dan data usaha tersimpan terpisah.",
    imageAlt: "Operasional warung yang dibantu TemanUsaha AI",
    customerRequest: "Pesan pelanggan",
    request: "“Catat 3 nasi ayam dan 2 es teh untuk Bu Rina.”",
    metrics: [["Rp55.000", "Pesanan"], ["−5 item", "Stok"], ["Tercatat", "Aktivitas"]],
    workflow: "Satu alur kerja",
    benefitsTitle: "Yang penting, langsung terlihat.",
    benefitsIntro: "Mulai dari demo sintetis, lalu gunakan dashboard pribadi untuk usaha Anda sendiri.",
    benefits: [
      ["Pesanan tercatat", "Catat pesanan dari percakapan tanpa menyalin data dua kali."],
      ["Stok terpantau", "Lihat stok menipis dan perubahan produk dalam satu tempat."],
      ["Tindakan AI terlihat", "Periksa setiap tindakan penting sebelum mempercayai hasilnya."],
    ],
    facts: ["6 Action operasional aktif", "Pesanan dan stok diperbarui bersamaan", "Setiap perubahan memiliki jejak aktivitas"],
  },
  en: {
    signIn: "Sign in",
    language: "Language",
    eyebrow: "Operations assistant for MSMEs",
    title: "Manage orders and inventory through conversation.",
    description: "TemanUsaha connects GPT to your business data, keeping orders, inventory, and daily summaries organized and auditable.",
    demoCta: "Try the interactive demo",
    dashboardCta: "Open your business dashboard",
    deployCta: "Deploy your own",
    separation: "Demo data and business data stay separate.",
    imageAlt: "A small food business supported by TemanUsaha AI",
    customerRequest: "Customer request",
    request: "“Record 3 chicken rice meals and 2 iced teas for Bu Rina.”",
    metrics: [["Rp55,000", "Order"], ["−5 items", "Inventory"], ["Logged", "Activity"]],
    workflow: "One workflow",
    benefitsTitle: "See what matters immediately.",
    benefitsIntro: "Start with synthetic demo data, then use a private dashboard for your own business.",
    benefits: [
      ["Orders captured", "Turn conversations into orders without copying the same data twice."],
      ["Inventory monitored", "See low stock and product changes in one place."],
      ["AI actions visible", "Review every important action before relying on the result."],
    ],
    facts: ["6 operational Actions available", "Orders and inventory update together", "Every change has an activity trail"],
  },
  fr: {
    signIn: "Se connecter",
    language: "Langue",
    eyebrow: "Assistant opérationnel pour TPE et PME",
    title: "Gérez commandes et stocks par la conversation.",
    description: "TemanUsaha relie GPT aux données de votre entreprise pour garder commandes, stocks et bilans quotidiens organisés et vérifiables.",
    demoCta: "Essayer la démo",
    dashboardCta: "Ouvrir le tableau de bord",
    deployCta: "Déployer votre version",
    separation: "Les données de démo et de votre entreprise restent séparées.",
    imageAlt: "Une petite entreprise de restauration assistée par TemanUsaha AI",
    customerRequest: "Demande client",
    request: "« Enregistrez 3 riz au poulet et 2 thés glacés pour Bu Rina. »",
    metrics: [["55 000 Rp", "Commande"], ["−5 articles", "Stock"], ["Consignée", "Activité"]],
    workflow: "Un seul flux",
    benefitsTitle: "L’essentiel, visible immédiatement.",
    benefitsIntro: "Commencez avec la démo synthétique, puis utilisez un tableau de bord privé pour votre entreprise.",
    benefits: [
      ["Commandes consignées", "Transformez la conversation en commande sans recopier les données."],
      ["Stock surveillé", "Repérez les stocks faibles et les changements de produits au même endroit."],
      ["Actions IA visibles", "Vérifiez chaque action importante avant de vous fier au résultat."],
    ],
    facts: ["6 Actions opérationnelles disponibles", "Commandes et stocks se mettent à jour ensemble", "Chaque modification laisse une trace"],
  },
  ja: {
    signIn: "ログイン",
    language: "言語",
    eyebrow: "中小企業・小規模事業者向け業務アシスタント",
    title: "会話から注文と在庫を管理。",
    description: "TemanUsaha は GPT と事業データをつなぎ、注文・在庫・日次サマリーを整理し、あとから確認できる状態に保ちます。",
    demoCta: "デモを試す",
    dashboardCta: "事業ダッシュボードを開く",
    deployCta: "自分用にデプロイ",
    separation: "デモデータと事業データは分離して保存されます。",
    imageAlt: "TemanUsaha AI を活用する小規模飲食店",
    customerRequest: "お客様の依頼",
    request: "「Bu Rina 様に鶏飯3つとアイスティー2つを記録して。」",
    metrics: [["Rp55,000", "注文"], ["−5品", "在庫"], ["記録済み", "履歴"]],
    workflow: "ひとつの業務フロー",
    benefitsTitle: "必要な情報を、すぐ見える形に。",
    benefitsIntro: "合成データのデモから始め、自社専用の非公開ダッシュボードへ移行できます。",
    benefits: [
      ["注文を自動記録", "会話から注文を作成し、同じデータの二重入力をなくします。"],
      ["在庫を一元管理", "在庫不足と商品変更をひとつの画面で確認できます。"],
      ["AI操作を可視化", "重要な操作を履歴で確認してから結果を利用できます。"],
    ],
    facts: ["6つの業務Actionに対応", "注文と在庫を同時更新", "すべての変更に操作履歴"],
  },
} as const;
